### ISSUE TITLE
padding in nested tables

### ISSUE THREAD

**Issue by martin19** [phax/ph-pdf-layout#21]
Hi @phax,

I might have found a bug with nested tables.

The outer table has two columns and n rows. The table spans multiple pages (this might not be relevant though)
Each row is set up like this:
- in the first column there is a cell with a few mm padding (new PLCell(new PLText).setPadding(x) 
- in the second column there is a nested table with n rows, two columns and no padding.

It seems the first cells paddings are not respected in the second columns cell height computation - the cells in each row do not align vertically, the first column is higher in total (I assume by 2*padding).
When I remove the first cell's padding the cells are aligned vertically.

I'll provide a test case if that is required. 

![image](https://user-images.githubusercontent.com/4746984/129362574-ae2155e5-c4c2-471e-909d-59198c69b28e.png)

**Comment by phax** [comment]
@martin19  thanks for pointing that out. I added a small example snippet that should outline the issue.
When I run this, it creates the following output:
[issue21.pdf](https://github.com/phax/ph-pdf-layout/files/6991472/issue21.pdf)

If you are referring to the issue, that the cell border is "broken", than I would say, that works as designed, because the next row starts again evenly. The height of the row is the maximum height of the contained cells. But the border is pained around each cell, and not around each row.

The only error that I could discover is the bottom padding of the inner table - depicted with a black block in the below image:
![grafik](https://user-images.githubusercontent.com/196219/129547981-24f0069d-a79c-4d91-8b88-152b5e8bbee5.png)

So please clarify what exactly your expectations are.
If you dislike the border than I recommend to change `new PLTableCell (new PLText (...)).setPadding` to `new PLTableCell (new PLBox (new PLText (...)).setPadding ())` - so to wrap the text in a "PLBox" and put the padding on the box instead,
See this PDF for comparison: 
[issue21a.pdf](https://github.com/phax/ph-pdf-layout/files/6991513/issue21a.pdf)
Looking like this:
![grafik](https://user-images.githubusercontent.com/196219/129548535-55820fb7-38e4-4ebc-aecc-5834629b531d.png)

hth

**Comment by martin19** [comment]
hi @phax I've found the solution you mention by putting the padding on the inner element of the cell, thanks for pointing that out. I think I expected all cells in a row to have equal height always (including borders like html tables). You can call this a feature to have this kind of staircase table - I don't wanna bargain on that. The reason I'm doing all this is to "emulate" rowspan/colspan: the inner table has no outer border so it beautifully blends with the cell borders of the outer table - Is there a better way to do this?

I've only had some minor issues (yet) that might interest you:
- otf fonts don't seem to work with the library (there is an exception thrown) while ttf files work well
- sometimes there are "blank" pages in the PDF (I assume there might be some margin of another element above on this page). I'll need to debug that.
- had a bit of a hard time to implement a full size page header with page margin - I finally got it to work with document padding

Thanks you for your work.

**Comment by phax** [comment]
Thanks for your feedback.
What you may want to emulate is "padding" on the row of the outer table I guess. This can be done by calling `setPadding` which will effectively set it on all contained cells...
* Regarding the fonts: I am limited on what is offered by the FontBox project which is part of PDFBox - http://pdfbox.apache.org/ - I recommend you place any features requests there
* Regarding the blank pages: with `PLDebugRender.setDebugRender(true)` you can create helper lines etc. that might help you identify the issue. It outlines page sets, block elements and inline elements with different colors. With class `PLDebugLog` you can increate debug logging.
* What do you mean with "Full size page header" - you mean spawning the full width? But anyway, glad you were able to resolve it....
*

**Comment by martin19** [comment]
Hi @phax, thank you for the setDebugRender tip. That will probably make it lots easier to see what is going on. With full size header I actually meant full-width. 

There is a problem I've been thinking about. Is it possible to determine the actual position of the currently rendered object in the page? I'd like to implement a policy for inserting page breaks depending on the amount of content that is on the current page. If yes - great - if no what would be the effort to implement such thing. 

Thank you!
